"""Add plan_edit table for chat-driven plan updates

Revision ID: 28517a25d242
Revises: 34d8d86c863e
Create Date: 2026-03-04 14:35:02.841966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28517a25d242'
down_revision = '34d8d86c863e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_edit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('assistant_reply', sa.Text(), nullable=True),
    sa.Column('edit_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['wayfinder_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_edit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_edit_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_edit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_edit_submission_id'))

    op.drop_table('plan_edit')
    # ### end Alembic commands ###
